version: "3.7"

services:
  database:
    image: mysql:8.0
    platform: linux/amd64
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_DATABASE=codetest
      - MYSQL_USER=codetest
      - MYSQL_PASSWORD=1333
      - MYSQL_ROOT_PASSWORD=1333
    ports:
      - "8081:8081"
    restart: always

  example-python:
    image: example-python
    build: images/example-python
    command: ["./example.py"]
    volumes:
      - ./data:/data
